name: Java Hello World

on: [push, workflow_dispatch]

jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21" # or "17"

      - name: Compile & run
        run: javac Hello.java && java Hello
